version: '3.1'
services:
  mockapi:
    image: m2tx/gomockapi:v1.2.0
    restart: always
    environment:
      LOGGER_LEVEL: INFO
      PORT: 9999
    volumes:
        - "./config.json:/config.json"
    ports:
      - 9999:9999
