version: '3'
services:
  postgres12:
      image: postgres:12-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
      healthcheck:
       test: [ "CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "keycloak" ]
       timeout: 45s
       interval: 20s
       retries: 5
      deploy:
       restart_policy:
        condition: on-failure
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      healthcheck:
       test: "curl --fail --silent http://localhost:8080/health | grep UP || exit 1"
       interval: 30s
       timeout: 30s
       retries: 3
       start_period: 30s
      environment:
        - "KC_HEALTH_ENABLED=true"
        - "KC_DB=postgres"
        - "KC_DB_URL=jdbc:postgresql://postgres12:5432/keycloak"
        - "KC_DB_SCHEMA=public"
        - "KC_DB_USERNAME=keycloak"
        - "KC_DB_PASSWORD=password"
        - "KEYCLOAK_ADMIN=admin"
        - "KEYCLOAK_ADMIN_PASSWORD=password"
        - "PROXY_ADDRESS_FORWARDING=true"
      entrypoint: /opt/keycloak/bin/kc.sh start-dev
      ports:
        - 8080:8080
      depends_on:
        - postgres12
volumes:
  postgres_data:
      driver: local
