version: "3.9"

services:
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  grafana_data:
    driver: local