version: "2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - "rabbitmq_data:/var/lib/rabbitmq/"
        - "rabbitmq_log:/var/log/rabbitmq/"
volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
